# Generated by Django 3.2.6 on 2021-12-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('evaluations', '0002_alter_rating_unique_together'), ('evaluations', '0003_alter_rating_date')]

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
