# Generated by Django 3.2.6 on 2021-12-08 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_alter_movie_homepage'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('movie', 'user')},
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
