# Generated by Django 3.2.6 on 2021-09-25 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


def add_role(apps, schema_editor):
    Roles = apps.get_model("users", "RolesUser")
    dict_role = [
        {'order': 1, 'role_name': 'Użytkownik'},
        {'order': 10, 'role_name': 'Administrator'}
    ]
    for role in dict_role:
        x = Roles(order=role['order'], role_name=role['role_name'])
        x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('role_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'users_roles_user',
            },
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 20, 54, 8, 624305)),
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='users.rolesuser'),
        ),
        migrations.RunPython(add_role),
    ]
