# Generated by Django 3.2.6 on 2021-12-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211006_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatarURL',
            new_name='avatar_url',
        ),
    ]
