# Generated by Django 3.2.6 on 2021-10-17 22:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='photos.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso_3166_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('iso_639_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MovieStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'movies_movie_status',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('surname', models.CharField(blank=True, default='', max_length=150)),
                ('gender', models.IntegerField(choices=[(0, 'Nieokreślona'), (1, 'Kobieta'), (2, 'Mężczyzna')], default=0)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='photos.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('original_title', models.CharField(default='', max_length=130)),
                ('release_date', models.DateField(default=None, null=True)),
                ('runtime', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1, message='Film musi trwać min 1 min.')])),
                ('budget', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('homepage', models.URLField(default=True, max_length=500, null=True)),
                ('adult', models.BooleanField(default=False)),
                ('video', models.BooleanField(default=False)),
                ('overview', models.TextField(default='', max_length=1500)),
                ('tagline', models.TextField(default='', max_length=500)),
                ('revenue', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('average_vote', models.FloatField(default=0)),
                ('count_vote', models.IntegerField(default=0)),
                ('visibility', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='movies.collection')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='photos.gallery')),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('keywords', models.ManyToManyField(to='movies.Keyword')),
                ('original_language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='FK_original_language', to='movies.language')),
                ('production_companies', models.ManyToManyField(to='movies.Company')),
                ('production_countries', models.ManyToManyField(to='movies.Country')),
                ('spoken_languages', models.ManyToManyField(related_name='FK_spoken_languages', to='movies.Language')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='movies.moviestatus')),
            ],
            options={
                'unique_together': {('title', 'original_title', 'collection', 'release_date')},
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=80)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies.person')),
            ],
            options={
                'unique_together': {('movie_id', 'department', 'job', 'person')},
            },
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies.person')),
            ],
            options={
                'unique_together': {('movie', 'character', 'person')},
            },
        ),
    ]
