# Generated by Django 3.2.6 on 2021-12-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211128_2200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crew',
            unique_together={('movie', 'department', 'job', 'person')},
        ),
    ]
