# Generated by Django 3.2.6 on 2021-12-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_crew_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
    ]
